version: "3"

volumes:
  database:

services:
  db:
    image: postgres:12.2-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data

  web:
    build: .
    environment:
      TZ: Asia/Tokyo
      RAILS_ENV: development
      RACK_ENV: development
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: yabe_development
      DB_HOST: db
      RAILS_LOG_TO_STDOUT: enabled
      BINDING: 0.0.0.0
    ports:
      - 3000:3000
    volumes:
      - .:/app:cached
    tmpfs:
      - /app/tmp
      - /tmp
    depends_on:
      - db
